### ISSUE TITLE
请问这播放器还能用吗，启动以后全是报错啊（后端已经开启）：什么“音频不可用 ”

### ISSUE THREAD

**Issue by mebest100** [daoshengfu/vue-fds_music#3]
请问这播放器还能用吗，启动以后全是报错啊（后端已经开启）：什么“音频不可用 ”

![image](https://user-images.githubusercontent.com/11530991/90996565-b4b71d80-e5f1-11ea-9dc8-5e118c116d85.png)

**Comment by mebest100** [comment]
难道是因为后端接口的证书已过期的原因吗？

![image](https://user-images.githubusercontent.com/11530991/90996783-60606d80-e5f2-11ea-8419-250b46e6575b.png)

**Comment by daoshengfu** [comment]
!
![图片](https://user-images.githubusercontent.com/68282688/90996915-a5849f80-e5f2-11ea-9788-6a5c8d818d19.png)
我刚启动试了下，没问题的，我看你控制台报错好像全是后台错误，是不是后台没启动好

**Comment by mebest100** [comment]
后台的启动命令就是这个把：node app.js，唯一的区别就是没有进入api目录启动，因为当前根目录并没有这个文件夹：
我实在找不出还有哪个地方错了：

![image](https://user-images.githubusercontent.com/11530991/90997170-61de6580-e5f3-11ea-9581-b5855ae70112.png)

**Comment by daoshengfu** [comment]
![图片](https://user-images.githubusercontent.com/68282688/90997253-9f42f300-e5f3-11ea-89ee-b89202404252.png)
启动成功会有一个3000端口号，你浏览器地址栏输入localhost:3000看看有没有页面，测试下

**Comment by mebest100** [comment]
这个有的： 能不能请你git clone一下后端最新的代码，然后启动起来再配合你的前端试试呢


![image](https://user-images.githubusercontent.com/11530991/90997358-e7faac00-e5f3-11ea-93b6-26b4d2b3ddf5.png)

**Comment by cod-star** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;daoshengfu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月24日(星期一) 上午10:16
收件人:&nbsp;&quot;daoshengfu/vue-fds_music&quot;<vue-fds_music@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [daoshengfu/vue-fds_music] 请问这播放器还能用吗，启动以后全是报错啊（后端已经开启）：什么“音频不可用 ” (#3)

**Comment by daoshengfu** [comment]
![图片](https://user-images.githubusercontent.com/68282688/90999399-0a42f880-e5f9-11ea-97e8-c3be03081d74.png)
![图片](https://user-images.githubusercontent.com/68282688/90999406-12029d00-e5f9-11ea-8f14-ac2caa625f48.png)
我已经给后台升级到最新了，还是没问题

**Comment by mebest100** [comment]
我搜索了一下这个报错，网上说要在配置文件中设置：strictSSL: false，让nodejs忽略这种证书错误，
我不知道你是不是在你自己本地的前端配置文件中做了特别设定，否则我们两边结果不可能不一样。

**Comment by daoshengfu** [comment]
我的没有，它API官网也没说要配置，你自己配置试试吧

**Comment by mebest100** [comment]
关键是不知道这个这个忽略证书的配置应该写在哪个文件啊

**Comment by daoshengfu** [comment]
应该是vue.config.js这个文件

**Comment by mebest100** [comment]
好的，我试试看

**Comment by mebest100** [comment]
我修改了后端的request.js文件加入了strictSSL=false，虽然接口通了不报502错误，但是取不到正确的数据，返回非JSON数据：
![image](https://user-images.githubusercontent.com/11530991/91011820-96641880-e617-11ea-9e64-50c7deb0ecd8.png)


你能从你本地访问一下这两个接口，看看返回数据是否正常吗？

http://localhost:3000/search/hot/detail
http://localhost:3000/search?keywords=%E6%B5%B7%E9%98%94%E5%A4%A9%E7%A9%BA

**Comment by mebest100** [comment]
找到原因了，原来是路由器开启了解锁网易云音乐的原因，关了就好了。
